"use client";

import React, { useState } from 'react';
import { useAdminDraftStore } from '@/store/adminDraftStore';
import { Flag, Save, CheckCircle2, Bot, FileText, Download, GraduationCap, Bell, Sparkles } from 'lucide-react';
import flagsDefault from '@/content/feature-flags.json';

const flagDescriptions: Record<string, { label: string; desc: string; icon: React.ComponentType<any> }> = {
  ai_optimizer: {
    label: 'AI Resume Bullet Optimizer',
    desc: 'Controls Google Gemini AI rewrite buttons across work and project bullet inputs.',
    icon: Bot,
  },
  docx_export: {
    label: 'Word (.docx) Document Export',
    desc: 'Controls whether users can download their resume/CV in Microsoft Word (.docx) format.',
    icon: Download,
  },
  pdf_export: {
    label: 'Vector PDF Document Export',
    desc: 'Controls vector PDF downloads generated by @react-pdf rendering engine.',
    icon: FileText,
  },
  cv_mode: {
    label: 'Academic CV Workspace Mode',
    desc: 'Enables 14 specialized academic sections (publications, grants, teaching, ORCID).',
    icon: GraduationCap,
  },
  announcement_banner: {
    label: 'Global Notification Banner',
    desc: 'Displays the top announcement notification bar across all public website pages.',
    icon: Bell,
  },
  ats_score_badge: {
    label: 'ATS Compatibility Score Badges',
    desc: 'Shows ATS rating percentage badges (e.g. 98%) on template showcase cards.',
    icon: Sparkles,
  },
};

export default function FeatureFlagsCMS() {
  const { stageFile, stagedFiles } = useAdminDraftStore();

  const [flags, setFlags] = useState<Record<string, boolean>>(() => {
    if (stagedFiles['content/feature-flags.json']) {
      try {
        return JSON.parse(stagedFiles['content/feature-flags.json'].content);
      } catch { }
    }
    return flagsDefault;
  });

  const [saved, setSaved] = useState(false);

  const handleToggle = (key: string) => {
    setFlags((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const handleStage = () => {
    stageFile('content/feature-flags.json', JSON.stringify(flags, null, 2), 'Feature Flags Configuration');
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-5">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <Flag className="text-amber-400" size={20} />
            <span>Feature Flags & Remote Switches</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Toggle platform capabilities on or off with zero code modifications. Changes deploy on next push.
          </p>
        </div>

        <button
          onClick={handleStage}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold transition-all shadow-md shadow-blue-500/20"
        >
          {saved ? (
            <>
              <CheckCircle2 size={14} className="text-emerald-300" />
              <span>Staged in Draft!</span>
            </>
          ) : (
            <>
              <Save size={14} />
              <span>Stage Changes</span>
            </>
          )}
        </button>
      </div>

      <div className="space-y-3">
        {Object.entries(flags).map(([key, enabled]) => {
          const meta = flagDescriptions[key] || {
            label: key,
            desc: `Controls platform setting "${key}"`,
            icon: Flag,
          };
          const Icon = meta.icon;

          return (
            <div
              key={key}
              className="p-5 rounded-2xl bg-slate-900/40 border border-slate-800/80 flex items-center justify-between gap-4"
            >
              <div className="flex items-start gap-3.5">
                <div
                  className={`p-2.5 rounded-xl border mt-0.5 ${enabled
                      ? 'bg-blue-500/10 border-blue-500/20 text-blue-400'
                      : 'bg-slate-950 border-slate-800 text-slate-500'
                    }`}
                >
                  <Icon size={18} />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-white">{meta.label}</span>
                    <span className="text-[10px] font-mono text-slate-500">({key})</span>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">{meta.desc}</p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => handleToggle(key)}
                className={`relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${enabled ? 'bg-blue-600' : 'bg-slate-800'
                  }`}
              >
                <span
                  className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${enabled ? 'translate-x-5' : 'translate-x-0'
                    }`}
                />
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
}
