"use client";

import React, { useState } from 'react';
import { useAdminDraftStore } from '@/store/adminDraftStore';
import { useDraftState } from '@/hooks/useDraftState';
import { PageHeader, Toggle } from '@/components/admin/ui';
import { Flag, Bot, FileText, Download, GraduationCap, Bell, Sparkles } from 'lucide-react';
import flagsDefault from '@/content/feature-flags.json';

const flagDescriptions: Record<string, { label: string; desc: string; icon: React.ComponentType<any> }> = {
  ai_optimizer: {
    label: 'AI Resume Bullet Optimizer',
    desc: 'Controls Google Gemini AI rewrite buttons across work and project bullet inputs.',
    icon: Bot,
  },
  docx_export: {
    label: 'Word (.docx) Document Export',
    desc: 'Controls whether users can download their resume/CV in Microsoft Word (.docx) format.',
    icon: Download,
  },
  pdf_export: {
    label: 'Vector PDF Document Export',
    desc: 'Controls vector PDF downloads generated by @react-pdf rendering engine.',
    icon: FileText,
  },
  cv_mode: {
    label: 'Academic CV Workspace Mode',
    desc: 'Enables 14 specialized academic sections (publications, grants, teaching, ORCID).',
    icon: GraduationCap,
  },
  announcement_banner: {
    label: 'Global Notification Banner',
    desc: 'Displays the top announcement notification bar across all public website pages.',
    icon: Bell,
  },
  ats_score_badge: {
    label: 'ATS Compatibility Score Badges',
    desc: 'Shows ATS rating percentage badges (e.g. 98%) on template showcase cards.',
    icon: Sparkles,
  },
};

export default function FeatureFlagsCMS() {
  const { stageFile } = useAdminDraftStore();
  const [flags, setFlags] = useDraftState<Record<string, boolean>>('content/feature-flags.json', flagsDefault);
  const [saved, setSaved] = useState(false);

  const handleToggle = (key: string) => {
    setFlags((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const handleStage = () => {
    stageFile('content/feature-flags.json', JSON.stringify(flags, null, 2), 'Feature Flags Configuration');
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <PageHeader
        icon={Flag}
        iconColor="text-amber-600 dark:text-amber-400"
        title="Feature Flags & Remote Switches"
        description="Toggle platform capabilities on or off with zero code modifications. Changes deploy on next push."
        onStage={handleStage}
        saved={saved}
      />

      <div className="space-y-3">
        {Object.entries(flags).map(([key, enabled]) => {
          const meta = flagDescriptions[key] || {
            label: key,
            desc: `Controls platform setting "${key}"`,
            icon: Flag,
          };
          const Icon = meta.icon;

          return (
            <div
              key={key}
              className="p-5 rounded-2xl bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800/80 flex items-center justify-between gap-4 shadow-sm dark:shadow-none"
            >
              <div className="flex items-start gap-3.5 flex-1">
                <div
                  className={`p-2.5 rounded-xl border mt-0.5 ${
                    enabled
                      ? 'bg-blue-500/10 border-blue-500/30 text-blue-600 dark:text-blue-400'
                      : 'bg-slate-100 dark:bg-slate-950 border-slate-200 dark:border-slate-800 text-slate-400 dark:text-slate-500'
                  }`}
                >
                  <Icon size={18} />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-slate-900 dark:text-white">{meta.label}</span>
                    <span className="text-[10px] font-mono text-slate-500">({key})</span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-400 mt-1 font-normal">{meta.desc}</p>
                </div>
              </div>

              <Toggle
                checked={enabled}
                onChange={() => handleToggle(key)}
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}
